const UserRouter = require('./UserRouter')
const CourseRouter = require('./CourseRouter')
const OrderRouter = require('./OrderRouter')
const ScheduleRouter = require('./ScheduleRouter')
const ClassRouter = require('./ClassRouter')
const AttendanceRouter = require('./AttendanceRouter')
const ReviewRouter = require('./ReviewRouter')
const ExamRouter = require('./ExamRouter')
const ScoreRouter = require('./ScoreRouter')
const BlogRouter = require('./BlogRouter')
const PaymentRouter = require('./PaymentRouter')
const SuggestCourse = require('./CourseSuggestion')
const Notification = require('./NotificationRouter')
const Statisfic = require('./StatisticRouter')

const routes = (app) => {
    app.use('/api/user', UserRouter)
    app.use('/api/course', CourseRouter)
    app.use('/api/order', OrderRouter)
    app.use('/api/schedule', ScheduleRouter)
    app.use('/api/class', ClassRouter)
    app.use('/api/attendance', AttendanceRouter)
    app.use('/api/review', ReviewRouter)
    app.use('/api/exam', ExamRouter)
    app.use('/api/score', ScoreRouter)
    app.use('/api/blog', BlogRouter)
    app.use('/api/payment', PaymentRouter)
    app.use('/api/suggest-course', SuggestCourse)
    app.use('/api/notification', Notification)
    app.use('/api/statistics', Statisfic)
}

module.exports = routes